// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoZqd3X8dd4_CdjRpki6JTwMfum9uv6H8',
    appId: '1:26232255043:web:3f0a1f30237c3df5fd1af6',
    messagingSenderId: '26232255043',
    projectId: 'chat-app-79e64',
    authDomain: 'chat-app-79e64.firebaseapp.com',
    storageBucket: 'chat-app-79e64.appspot.com',
    measurementId: 'G-ZJKEJ6R2KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6XlzfHbF9UJfa9L9TdavI0WgRay9nUCw',
    appId: '1:26232255043:android:34bf0f074dfa4751fd1af6',
    messagingSenderId: '26232255043',
    projectId: 'chat-app-79e64',
    storageBucket: 'chat-app-79e64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk1t6ytjC5eyGPt_m4TY9ykBXK2MeoKzU',
    appId: '1:26232255043:ios:a54297f2f5d72b1ffd1af6',
    messagingSenderId: '26232255043',
    projectId: 'chat-app-79e64',
    storageBucket: 'chat-app-79e64.appspot.com',
    iosClientId: '26232255043-l7mipnfon9s7bdjrfmoih1k2rfulvbhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk1t6ytjC5eyGPt_m4TY9ykBXK2MeoKzU',
    appId: '1:26232255043:ios:a54297f2f5d72b1ffd1af6',
    messagingSenderId: '26232255043',
    projectId: 'chat-app-79e64',
    storageBucket: 'chat-app-79e64.appspot.com',
    iosClientId: '26232255043-l7mipnfon9s7bdjrfmoih1k2rfulvbhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
